### ISSUE TITLE
Error when adding default filtering

### ISSUE THREAD

**Issue by minhkhoablieu** [nvmcommunity/alchemist-restful-api#2]
Version: [2.0.20](https://github.com/nvmcommunity/alchemist-restful-api/releases/tag/2.0.20)

when i add default filtering using addFilteringIfNotExists function

```php
public static function resourceFilter(ResourceFilter $resourceFilter): void
    {
        $resourceFilter->defineFilteringRules([
            FilteringRules::String('id', ['eq']),
            FilteringRules::String('key', ['eq', 'contains']),
        ]);

        $resourceFilter->addFilteringIfNotExists('value', 'eq', 1);
    }
```

It reports an error as shown below
![image](https://github.com/user-attachments/assets/4d1b8454-d5e6-4b59-9147-94dd5f368b70)

Please help me.
Thanks

**Comment by skillaug** [comment]
The behavior of the `addFilteringIfNotExists()` function expects that the developer has declared the filtering through `defineFilteringRules()`. This means that if the client does not provide filtering, the library will automatically use default filtering data. In this context, it is mandatory for the user to be able to provide filtering.

The library itself cannot automatically define this filtering in the list of valid filtering because it lacks information about the data type of the filtering, and the data type is necessary to declare valid filtering.

To resolve this issue, you need to explicitly declare filtering using the `defineFilteringRules()` function.

Thanks and best regards.
